name: CI/CD to Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and tag Docker image
        run: docker build -t gcr.io/quest-408401/quest:${{ github.sha }} .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.0.0
        with: 
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Debug GITHUB_SHA
        run: echo "GITHUB_SHA is $GITHUB_SHA"


      - name: Terraform Init
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          github_sha: $GITHUB_SHA
        run: terraform init

      - name: Deploy to Cloud Run
        env:
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          github_sha: $GITHUB_SHA
        run: terraform apply -auto-approve
