name: CI/CD to Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and tag Docker image
        run: |
             docker build -t ghcr.io/apitanga/quest:${{ github.sha }} .
             docker tag ghcr.io/apitanga/quest:${{ github.sha }} ghcr.io/apitanga/quest:${{ github.sha }}

      - name: Set up Google Cloud credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2.0.0
        with: 
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Push image to GCR (optional)
        run: gcloud docker -- push ghcr.io/apitanga/quest:prod

      - name: Fetch Terraform modules
        run: terraform init

      - name: Deploy to Cloud Run
        run: terraform apply -auto-approve --target cloutrun
