name: CI/CD to Cloud Run

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and tag Docker image
        run: |
             docker build -t ghcr.io/apitanga/quest:prod .
             docker tag ghcr.io/apitanga/quest:prod ghcr.io/apitanga/quest:prod

      - name: Set up Google Cloud credentials
        run: echo "${{ secrets.GCP_SA_KEY }}" > $HOME/gcp-key.json

      - name: Authenticate to Google Cloud
        run: gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

      - name: Push image to GCR (optional)
        run: gcloud docker -- push ghcr.io/apitanga/quest:prod

      - name: Fetch Terraform modules
        run: terraform init

      - name: Deploy to Cloud Run
        run: terraform apply -auto-approve --target cloutrun
